require_paths:
- /home/devlin/.wine-sketchup-2017/drive_c/SketchUp2017
- /home/devlin/.wine-sketchup-2017/drive_c/SketchUp2017/Tools
- src

require:
- sketchup-api-stubs

reporters:
- rubocop

# Exclude files that doesn't need to be parsed. Avoids noise and improve performance.
exclude:
- /build/**/*
- /ThirdParty/**/*
